### ISSUE TITLE
`prismfees` plugin method

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/bolt12-prism#17]
calculate what the fees will be to pay a prism ahead of time.

This could be a nice data point for some UI's

**Comment by farscapian** [comment]
In my opinion, this is out-of-scope for prisms. In lightning network, the sender pays fees to complete a payment. So there's nothing for us to worry about when RECEIVING a payment to a Prism--only when we payout to a receiver share. Since we are dealing with payment flows, we should simply account for the fees incurred as we go along. We should assume that core lightning is making intelligent decisions to minimize fees at the time of payment.

**Comment by daGoodenough** [comment]
The fees to pay each prism member should be paid by the user paying the prism, not the prism node. And the sender would only have an idea of the fee to pay to the prism, but what if there are 100 prism members? Assuming fees comparable, that would be a 100x fee from what they thought they were paying. 
In my opinion, if the prism node is going be accounting for fees, then the sender should know what fees will be incurred.

**Comment by farscapian** [comment]
I definitely think that's out of scope. The user on a remote lightning node who pays to a Prism offer incurs the fees to pay to the Prism. From their perspective, they are paying a single lightning node. The BOLT12 Offer may or may not represent a Prism.

The design i prefer is one in which we are batching payments; it's not like every incoming payment to a Prism results in a payout for every member of that prism. Outlays are accrued until a payout threshold is reached and a payout occurs. Currently, fees from those payouts are paid by the Prism Owner by default, but we could instead account for payout fees in each prism member outlay value. In other words, payout fees are being deducted from future payouts for prism members resulting in Prisms members paying for fees for their payouts.

Furthermore, those prism members may have different outlay values and payout thresholds, values which may change over time. So I think providing an estimate would be difficult.
